In [1]:
import torch

In [17]:
scores = torch.rand(10,8)

In [18]:
scores

tensor([[0.1550, 0.1917, 0.4883, 0.6618, 0.3507, 0.1694, 0.7424, 0.3067],
        [0.1490, 0.4954, 0.0440, 0.5918, 0.4374, 0.2352, 0.7850, 0.4398],
        [0.7277, 0.1070, 0.9953, 0.0231, 0.0731, 0.2263, 0.4785, 0.7319],
        [0.4720, 0.6296, 0.5397, 0.6737, 0.2450, 0.6566, 0.3393, 0.4635],
        [0.7952, 0.6748, 0.2465, 0.2926, 0.9985, 0.6364, 0.6008, 0.4946],
        [0.2361, 0.7266, 0.1014, 0.2775, 0.9458, 0.1839, 0.8240, 0.8688],
        [0.7144, 0.3496, 0.3882, 0.8329, 0.1830, 0.9750, 0.5574, 0.7935],
        [0.5677, 0.4054, 0.2651, 0.4464, 0.5118, 0.4895, 0.9581, 0.9394],
        [0.1245, 0.5433, 0.0670, 0.7876, 0.6485, 0.9752, 0.5390, 0.8963],
        [0.0931, 0.7859, 0.3301, 0.8819, 0.6639, 0.2695, 0.5170, 0.8115]])

In [26]:
scores_min = (scores)

In [27]:
scores_min

tensor([[0.1550, 0.1917, 0.4883, 0.6618, 0.3507, 0.1694, 0.7424, 0.3067],
        [0.1490, 0.4954, 0.0440, 0.5918, 0.4374, 0.2352, 0.7850, 0.4398],
        [0.7277, 0.1070, 0.9953, 0.0231, 0.0731, 0.2263, 0.4785, 0.7319],
        [0.4720, 0.6296, 0.5397, 0.6737, 0.2450, 0.6566, 0.3393, 0.4635],
        [0.7952, 0.6748, 0.2465, 0.2926, 0.9985, 0.6364, 0.6008, 0.4946],
        [0.2361, 0.7266, 0.1014, 0.2775, 0.9458, 0.1839, 0.8240, 0.8688],
        [0.7144, 0.3496, 0.3882, 0.8329, 0.1830, 0.9750, 0.5574, 0.7935],
        [0.5677, 0.4054, 0.2651, 0.4464, 0.5118, 0.4895, 0.9581, 0.9394],
        [0.1245, 0.5433, 0.0670, 0.7876, 0.6485, 0.9752, 0.5390, 0.8963],
        [0.0931, 0.7859, 0.3301, 0.8819, 0.6639, 0.2695, 0.5170, 0.8115]])

In [32]:
rank = scores_min.argsort(dim=1, descending=True)

In [33]:
rank

tensor([[6, 3, 2, 4, 7, 1, 5, 0],
        [6, 3, 1, 7, 4, 5, 0, 2],
        [2, 7, 0, 6, 5, 1, 4, 3],
        [3, 5, 1, 2, 0, 7, 6, 4],
        [4, 0, 1, 5, 6, 7, 3, 2],
        [4, 7, 6, 1, 3, 0, 5, 2],
        [5, 3, 7, 0, 6, 2, 1, 4],
        [6, 7, 0, 4, 5, 3, 1, 2],
        [5, 7, 3, 4, 1, 6, 0, 2],
        [3, 7, 1, 4, 6, 2, 5, 0]])

In [54]:
cut = rank[:, :2]

In [34]:
position = torch.arange(2, 2+10)

In [37]:
position

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [95]:
label = torch.ones((2,10))

In [106]:
label[0, torch.arange(1, 10)] = 0. 
label[1, torch.arange(1, 10)] = 0 

In [107]:
label

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [108]:
cut = torch.LongTensor([
    [0,3,1,2,4,5,6,7,8,9],
    [1,2,0,3,4,5,6,7,8,9]
])

In [109]:
label

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [110]:
label.gather(1, cut)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [111]:
position = torch.arange(2, 2+10)
weights = 1 / torch.log2(position.float())

In [112]:
weights

tensor([1.0000, 0.6309, 0.5000, 0.4307, 0.3869, 0.3562, 0.3333, 0.3155, 0.3010,
        0.2891])

In [113]:
label

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [114]:
hits = label.gather(1, cut)

In [116]:
hits

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [118]:
hits

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [117]:
hits * weights

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])

In [75]:
label.gather(1, cut).sum(1) / label.sum(1)

tensor([1., 0.])